name: reactiontest
description: Test your reaction
publish_to: 'none'
version: 1.3.0+20
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.10
  shared_preferences: ^2.5.3

dev_dependencies:
  carapacik_lints: ^1.12.0
  #flutter_launcher_icons: ^0.14.4
  #flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path_android: 'assets/ic_logo_border.png'
  image_path_ios: 'assets/ic_logo.png'
  android: true
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  ios: true
  web:
    generate: true
    image_path: 'assets/ic_logo_border.png'
    background_color: '#0175C2'
  macos:
    generate: true
    image_path: 'assets/ic_logo_border.png'
  windows:
    generate: true
    image_path: 'assets/ic_logo_border.png'
    icon_size: 256
